spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jackson:
    time-zone: Asia/Seoul

  profiles:
    active:
      - local
    group:
      local:
        - oauth
        - db-local
      dev:
        - oauth
        - db-dev
    include: db, oauth

logging:
  level:
    org.springframework.security: DEBUG
    com.paekom: DEBUG

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: paekom
ai:
  server:
    url: ${AI_SERVER_URL}